# Generated by Django 5.0.4 on 2024-05-11 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourney_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.FloatField(default=0.0)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourney_reg.registration')),
            ],
            options={
                'ordering': ['registration', 'final_rank', 'final_score'],
            },
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_score', models.FloatField()),
                ('justification', models.TextField(blank=True, null=True)),
                ('final_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourney_scoring.finalscore')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourney_reg.profile')),
            ],
            options={
                'ordering': ['final_score', 'judge', 'judge_score'],
            },
        ),
        migrations.AddConstraint(
            model_name='finalscore',
            constraint=models.UniqueConstraint(fields=('registration', 'final_rank'), name='unique_registration_final_rank'),
        ),
        migrations.AddConstraint(
            model_name='finalscore',
            constraint=models.CheckConstraint(check=models.Q(('final_score__gte', 0), ('final_score__lte', 10)), name='final_score_range', violation_error_message='Score must be between 0 and 10'),
        ),
        migrations.AddConstraint(
            model_name='finalscore',
            constraint=models.CheckConstraint(check=models.Q(('final_rank__gte', 1)), name='rank_range', violation_error_message='Rank must be greater than 1'),
        ),
        migrations.AddConstraint(
            model_name='judgescore',
            constraint=models.UniqueConstraint(fields=('final_score', 'judge'), name='unique_judge_scoring'),
        ),
        migrations.AddConstraint(
            model_name='judgescore',
            constraint=models.CheckConstraint(check=models.Q(('judge_score__gte', 0), ('judge_score__lte', 10)), name='judge_score_range', violation_error_message='Score must be between 0 and 10'),
        ),
    ]
