# Generated by Django 5.0.4 on 2024-05-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalscore',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
