# Generated by Django 5.0.4 on 2024-05-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_profiles', '0001_initial'),
        ('tourney_scoring', '0002_alter_finalscore_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgescore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourney_profiles.profile'),
        ),
    ]
