# Generated by Django 5.0.4 on 2024-05-18 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_profiles', '0002_alter_profile_birth_date'),
        ('tourney_scoring', '0003_alter_judgescore_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='head_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_judge', to='tourney_profiles.profile'),
        ),
    ]
