# Generated by Django 5.0.4 on 2024-05-19 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_profiles', '0002_alter_profile_birth_date'),
        ('tourney_scoring', '0004_finalscore_head_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalscore',
            name='head_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_judge': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_judge', to='tourney_profiles.profile'),
        ),
        migrations.AlterField(
            model_name='judgescore',
            name='judge',
            field=models.ForeignKey(limit_choices_to={'is_judge': True}, on_delete=django.db.models.deletion.CASCADE, to='tourney_profiles.profile'),
        ),
    ]
