# Generated by Django 5.0.4 on 2024-05-19 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_scoring', '0005_alter_finalscore_head_judge_alter_judgescore_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalscore',
            name='final_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='judgescore',
            name='judge_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
