# Generated by Django 5.0.4 on 2024-05-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_scoring', '0006_alter_finalscore_final_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='final_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
