# Generated by Django 5.0.4 on 2024-05-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_profiles', '0001_initial'),
        ('tourney_reg', '0001_initial'),
        ('tourney_scoring', '0003_alter_judgescore_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='users',
            field=models.ManyToManyField(to='tourney_profiles.profile'),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='judges',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_judge': True}, to='tourney_profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
