# Generated by Django 5.0.4 on 2024-05-14 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_reg', '0002_alter_registrant_users_alter_tournamentevent_judges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentevent',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
