# Generated by Django 5.0.4 on 2024-05-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_reg', '0004_registration_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentevent',
            options={'ordering': ['tournament', 'mat_or_location', 'event', 'order']},
        ),
    ]
