# Generated by Django 5.0.4 on 2024-05-21 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_profiles', '0002_alter_profile_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usawkf_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('usawkf_id',), name='unique_usawkf_id', violation_error_message='This USAWKF ID is already in use.'),
        ),
    ]
